<?php
declare(strict_types=1);

use Loki\Base\Config\Config;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @version 1.1.8 */
/** @var Template $block */
/** @var Config $config */
/** @var SecureHtmlRenderer $secureRenderer */

$timeout = $block->getTimeout();
if (false === is_numeric($timeout) || $timeout < 0) {
    $config = $block->getConfig();
    $timeout = $config->getMessagesTimeout();
}

$script = <<<SCRIPT
    document.addEventListener('alpine:init', () => {
        Alpine.data('MessageComponent', () => ({
            messages: [],
            timeout: {$timeout},
            init() {
                Alpine.effect(() => {
                    this.messages = Alpine.store('Message').getMessages();
                });
            },
            hasMessages() {
                return this.messages.length > 0;
            },
            removeMessage() {
                const type = this.\$el.getAttribute('data-message-type');
                const text = this.\$el.getAttribute('data-message-text');
                Alpine.store('Message').removeMessage(type, text);
            },
        }));
    });
SCRIPT;
?>
<?= $secureRenderer->renderTag('script', [], $script, false); ?>
