<?php
declare(strict_types=1);

use Loki\Base\Config\Config;
use Magento\Framework\View\Element\Template;

/** @version 1.1.8 */
/** @var Template $block */
/** @var Config $config */

$timeout = $block->getTimeout();
if (false === is_numeric($timeout) || $timeout < 0) {
    $config = $block->getConfig();
    $timeout = $config->getMessagesTimeout();
}
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiMessagesComponent', () => ({
            messages: [],
            timeout: <?= (int)$timeout ?>,
            init() {
                Alpine.effect(() => {
                    this.messages = Alpine.store('LokiMessageStore').getMessages();
                });
            },
            hasMessages() {
                return this.messages.length > 0;
            },
            removeMessage() {
                const type = this.$el.getAttribute('data-message-type');
                const text = this.$el.getAttribute('data-message-text');
                Alpine.store('LokiMessageStore').removeMessage(type, text);
            },
        }));
    });
</script>
